### ISSUE TITLE
The directory '' does not exist. Want me to create the path?

### ISSUE THREAD

**Issue by kim366** [Sharlock93/CppBuilder#2]
![cppbuilder](https://cloud.githubusercontent.com/assets/7744660/24578202/f6553378-16db-11e7-8fac-f13b18fca8cb.PNG)

When I hit cancel, it reappears, when I click OK, it creates the project, but when I open the folder it just puts me in the 'Computer' section of Windows Explorer and there is no folder with the project name to be found.

**Comment by Sharlock93** [comment]
hmmm, could you post your settings file? and also which version of Sublime Text are you using?

**Comment by kim366** [comment]
Whoops, my bad. Didn't set `workspace_dir`. But then it asks me 5 times to create the folders. Is there a way to force it automatically?

**Comment by kim366** [comment]
Oh my god, this plugin is awesome! Why didn't I find it earlier? Also, you said "This is my first plugin"; I don't buy that :P

**Comment by Sharlock93** [comment]
Hey I'm glad you enjoy it xD to be honest I personally use vim now, but if you have any suggestions or any modifications, they are welcomed, but I have to dust off my python and sublime text systems, unfortunately there is no way to make it create all the folders with one time confirmation, this was literally my first project with python and plugin for sublime.
